name: doxygen-deploy

on:
  push:
    branches: [ main ]


jobs:
  # The job that will build
  deploy-mj_driver_board:
    
    # Defines the operating system for the virtual computer
    runs-on: ubuntu-latest

    # A list of steps to follow to complete the build (a list of commands to execute on the virtual computer)
    steps:

    # This is a predefined action that checks out a copy of your code
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install doxygen
      run: sudo apt-get install -y doxygen

    # Run Doxygen 
    - name: Run Doxygen
      working-directory: ${{github.workspace}}/MJ_Driver_Board/Software/DriverBoardDropwatcher
      run: doxygen

    # Deploy html output from Doxygen to ghpages branches- name: Deploy
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages                                   # The branch the action should deploy to.
        folder: ${{github.workspace}}/MJ_Driver_Board/Software/DriverBoardDropwatcher/html      # The folder the action should deploy.
    
